"""make incident reported_by nullable for auto-detection

Revision ID: eaa0d090ab78
Revises: 4e5c87fac63e
Create Date: 2026-05-14 18:24:56.612830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa0d090ab78'
down_revision: Union[str, None] = '4e5c87fac63e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'reported_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'reported_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
